/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant kfc = new Restaurant("KFC",5,"middle");
        Review note = new Review("very good","mark hamil",5);
        System.out.println(note.toString());


        System.out.println(kfc.toString());
        kfc.addReview("good service","stue",2);
        System.out.println(kfc.toString());


    }
}
